export const USERS_COLLECTION_NAME = 'users'
export const PLAYERS_COLLECTION_NAME = 'players'
export const FIELDS_COLLECTION_NAME = 'fields'
export const RESERVATION_COLLECTION_NAME = 'reservation'
export const TAGS_COLLECTION_NAME = 'tags'
export const FRIENDS_COLLECTION_NAME = 'friends'
export const INVITATIONS_COLLECTION_NAME = 'invitations'